apiVersion: v1
kind: Service
metadata: 
  name: node-port-service
  labels:
    app: rawan
spec:
  type: NodePort
  selector:
    app: rawan
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 30005

  
